version: 2.1
jobs:
  build:
    parameters:
      version:
        type: string
    machine:
      image: windows-server-2019-vs2019:<< parameters.version >>
      resource_class: windows.medium
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Download WiX  
          command: |
            (New-Object Net.WebClient).DownloadFile('https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe', $exePath)
            cmd /c start /wait "$exePath" /q
      - restore_cache:
          name: restore file
          keys:
            - hello-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}
      - save_cache:
          name: save cache
          key: hello-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}
          paths:
            - ~/cache/hello.txt

workflows:
  win-jobs:
    jobs:
      - build:
          matrix:
            parameters:
              version: ["2023.04.1", "2023.08.1"]
 
