version: 2.1
jobs:
  build:
    parameters:
      version:
        type: string
    machine:
      image: windows-server-2019-vs2019:<< parameters.version >>
      resource_class: windows.medium
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Download WiX  
          command: |
            $url = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
            $file = "$pwd\wix311.exe"
            $wc = New-Object System.Net.WebClient
            $wc.DownloadFile( $url, $file );
            Start-Process -Wait -FilePath "wix311.exe" -Argument "/silent" -PassThru
      - restore_cache:
          name: restore file
          keys:
            - hello-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}
      - save_cache:
          name: save cache
          key: hello-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}
          paths:
            - ~/cache/hello.txt

workflows:
  win-jobs:
    jobs:
      - build:
          matrix:
            parameters:
              version: ["2023.04.1", "2023.08.1"]
 
