version: 2.1
jobs:
  build:
    machine:
      image: windows-server-2019-vs2019
      shell: bash
    steps:
      - checkout
      - restore_cache:
          name: restore file
          keys:
            - hello-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}
      - save_cache:
          name: save cache
          key: hello-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}
          paths:
            - ~/cache/hello.txt

workflows:
  win-jobs:
    jobs:
      - build
 
